# ruff: noqa: E501, RUF001

REVIEW_HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Danbooru 标签翻译审核</title>
<style>
:root{color-scheme:light;--bg:#f4f6f8;--panel:#fff;--line:#dfe3e8;--text:#17212b;--muted:#68737f;--accent:#2463eb;--soft:#edf3ff;--danger:#a43d3d}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.5 system-ui,"Microsoft YaHei",sans-serif}
button,input,select{font:inherit}.page{max-width:1120px;margin:auto;padding:24px}.top{display:flex;gap:16px;align-items:end;justify-content:space-between;margin-bottom:18px}.top h1{font-size:24px;margin:0}.summary{color:var(--muted)}
.filters{display:grid;grid-template-columns:repeat(4,minmax(130px,1fr));gap:12px;padding:16px;background:var(--panel);border:1px solid var(--line);border-radius:14px;margin-bottom:16px}.field{display:grid;gap:5px}.field label{font-size:13px;color:var(--muted)}select,input{width:100%;min-height:44px;border:1px solid var(--line);border-radius:9px;background:#fff;color:var(--text);padding:8px 11px}select:focus-visible,input:focus-visible,button:focus-visible,a:focus-visible{outline:3px solid #93b4ff;outline-offset:2px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:16px;padding:22px;box-shadow:0 8px 28px rgba(26,35,50,.06)}.meta{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.tag{font:600 21px/1.3 ui-monospace,SFMono-Regular,Consolas,monospace;overflow-wrap:anywhere}.badge{padding:3px 9px;border-radius:99px;background:#eef0f3;color:#53606c;font-size:13px}.wiki{margin-left:auto;color:var(--accent)}
fieldset{border:0;padding:0;margin:0}legend{font-weight:600;margin-bottom:10px}.choice-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(260px,.72fr);gap:24px;margin:22px 0 16px}.candidates,.aliases{display:flex;flex-wrap:wrap;gap:9px}.references{display:grid;gap:12px;max-height:180px;overflow-y:auto;align-content:start}.reference-label{font-size:12px;color:var(--muted);margin-bottom:5px}.candidate{min-height:44px;padding:8px 13px;border:1px solid #cbd3dc;border-radius:10px;background:#f8fafc;color:var(--text);cursor:pointer;overflow-wrap:anywhere}.candidate:hover{background:var(--soft);border-color:#9eb9ee}.candidate.selected{background:#dce8ff;border-color:var(--accent);box-shadow:0 0 0 1px var(--accent) inset}.candidate small{color:var(--muted);margin-left:5px}.reference-item{display:inline-flex;min-height:44px}.reference-choice{min-height:44px;padding:6px 10px;border:1px solid var(--line);border-radius:9px;background:#f7f8fa;color:#596571;cursor:pointer;overflow-wrap:anywhere;text-align:left}.reference-choice:hover{background:var(--soft);border-color:#9eb9ee}.reference-choice:active{background:#e3edff}.reference-choice.selected{background:#dce8ff;border-color:var(--accent);box-shadow:0 0 0 1px var(--accent) inset}.reference-choice.wikipedia{color:#405d86;background:#f3f6fb;border-radius:9px 0 0 9px}.reference-choice.wikipedia.selected{background:#dce8ff}.reference-link{display:grid;place-items:center;min-width:44px;border:1px solid var(--line);border-left:0;border-radius:0 9px 9px 0;background:#f3f6fb;color:#405d86;text-decoration:none}.reference-link:hover{background:var(--soft)}.reference-link:active{background:#e3edff}.no-alias{color:var(--muted)}
.custom{display:grid;grid-template-columns:1fr auto;gap:10px;align-items:center}.length{min-width:54px;color:var(--muted)}.length.warn{color:var(--danger)}.actions,.nav{display:flex;flex-wrap:wrap;gap:10px;margin-top:18px}.actions button,.nav button{min-height:44px;border-radius:9px;padding:8px 15px;border:1px solid var(--line);background:#fff;cursor:pointer}.actions .primary{color:#fff;background:var(--accent);border-color:var(--accent)}button:hover{filter:brightness(.97)}button:active{filter:brightness(.92)}button:disabled{opacity:.45;cursor:not-allowed}.nav{justify-content:space-between;border-top:1px solid var(--line);padding-top:16px}.empty{text-align:center;color:var(--muted);padding:60px 20px}.message{min-height:24px;margin-top:12px;color:var(--muted)}.message.error{color:var(--danger)}
@media(max-width:720px){.page{padding:12px}.top{align-items:start;flex-direction:column}.filters{grid-template-columns:1fr 1fr}.card{padding:16px}.wiki{margin-left:0;width:100%}.choice-grid{grid-template-columns:1fr;gap:18px}.custom{grid-template-columns:1fr}.actions button{flex:1 1 140px}}
@media(max-width:440px){.filters{grid-template-columns:1fr}.candidate{width:100%;text-align:left}}
</style>
</head>
<body><main class="page">
<header class="top"><div><h1>标签翻译审核</h1><div class="summary" id="summary">正在加载…</div></div><div class="summary">数字键选择候选，Enter 保存</div></header>
<section class="filters" aria-label="筛选">
<div class="field"><label for="category">分类</label><select id="category"><option value="all">全部</option><option value="general">general</option><option value="copyright">copyright</option><option value="character">character</option><option value="meta">meta</option></select></div>
<div class="field"><label for="candidateStatus">候选数量</label><select id="candidateStatus"><option value="multiple_candidates">多个候选</option><option value="single_candidate">单个候选</option><option value="no_candidate">无中文候选（有 Wikipedia 参考）</option><option value="all">全部候选</option></select></div>
<div class="field"><label for="reviewStatus">审核状态</label><select id="reviewStatus"><option value="pending">待审核</option><option value="all">全部</option><option value="accept">已接受</option><option value="skip">暂时跳过</option><option value="no_suitable">无合适译名</option></select></div>
<div class="field"><label for="query">搜索 tag</label><input id="query" type="search" autocomplete="off" placeholder="例如 long_hair"></div>
</section>
<section class="card" id="card"><div class="empty">正在加载候选…</div></section>
</main>
<script>
const state={offset:0,item:null,selected:"",canUndo:false};const $=id=>document.getElementById(id);let timer;
function params(){return new URLSearchParams({offset:String(state.offset),category:$('category').value,candidate_status:$('candidateStatus').value,review_status:$('reviewStatus').value,q:$('query').value.trim()})}
async function load(){const res=await fetch('/api/item?'+params());const data=await res.json();if(!res.ok)throw Error(data.error||'加载失败');state.offset=data.offset;state.item=data.item;state.selected=data.item?.decision?.translation||'';state.canUndo=data.can_undo;$('summary').textContent=`${data.total?data.offset+1:0} / ${data.total}`;render()}
function render(){const card=$('card');card.replaceChildren();if(!state.item){const e=document.createElement('div');e.className='empty';e.textContent='当前筛选条件下没有待审核项目';card.append(e);if(state.canUndo){const actions=document.createElement('div');actions.className='actions';actions.append(actionButton('撤销上一条','',undo));card.append(actions)}return}const i=state.item;const meta=document.createElement('div');meta.className='meta';const tag=document.createElement('div');tag.className='tag';tag.textContent=i.tag;meta.append(tag);for(const text of [i.category,i.post_count.toLocaleString()+' posts']){const b=document.createElement('span');b.className='badge';b.textContent=text;meta.append(b)}if(i.decision?.source?.endsWith('_inferred')){const inferred=document.createElement('span');inferred.className='badge';inferred.textContent=i.decision.source==='wikipedia_inferred'?'Wikipedia 自动推断':'Wiki 自动推断';meta.append(inferred)}const link=document.createElement('a');link.className='wiki';link.href=i.source_url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='打开 Wiki';meta.append(link);card.append(meta);
const grid=document.createElement('div');grid.className='choice-grid';const fs=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent='选择候选译名';fs.append(legend);const list=document.createElement('div');list.className='candidates';i.candidates.forEach((value,index)=>{const b=document.createElement('button');b.type='button';b.className='candidate'+(state.selected===value?' selected':'');b.dataset.value=value;b.setAttribute('aria-pressed',String(state.selected===value));b.append(document.createTextNode(`${index+1}. ${value}`));const small=document.createElement('small');small.textContent=`${[...value].length}字`;b.append(small);b.onclick=()=>select(value);list.append(b)});fs.append(list);grid.append(fs);const refs=document.createElement('fieldset');const refsLegend=document.createElement('legend');refsLegend.textContent='其他名称（参考）';refs.append(refsLegend);const references=document.createElement('div');references.className='references';if(i.reference_aliases.length)references.append(referenceGroup('Wiki 其他语言别名',i.reference_aliases,false));if(i.wikipedia_references.length)references.append(referenceGroup('Wikipedia 中文标题',i.wikipedia_references,true));if(!i.reference_aliases.length&&!i.wikipedia_references.length){const empty=document.createElement('span');empty.className='no-alias';empty.textContent='没有其他参考名称';references.append(empty)}refs.append(references);grid.append(refs);card.append(grid);
const custom=document.createElement('div');custom.className='custom';const input=document.createElement('input');input.id='translation';input.placeholder='也可以输入更准确、更简短的译名';input.value=state.selected;input.maxLength=80;input.oninput=()=>{state.selected=input.value.trim();updateSelection();updateLength()};const len=document.createElement('span');len.id='length';len.className='length';custom.append(input,len);card.append(custom);updateLength();
const actions=document.createElement('div');actions.className='actions';actions.append(actionButton('保存译名','primary',()=>save('accept')));const undoButton=actionButton('撤销上一条','',undo);undoButton.disabled=!state.canUndo;actions.append(undoButton,actionButton('暂时跳过','',()=>save('skip')),actionButton('无合适译名','',()=>save('no_suitable')),actionButton('沿用原词','',()=>useOriginal(i.tag)));if(i.decision&&!i.decision.source?.endsWith('_inferred'))actions.append(actionButton('清除决定','',()=>save('clear')));card.append(actions);const msg=document.createElement('div');msg.id='message';msg.className='message';if(i.decision)msg.textContent=`${i.decision.source?.endsWith('_inferred')?'自动推断':'已记录'}：${label(i.decision.action)}${i.decision.translation?' · '+i.decision.translation:''}`;card.append(msg);
const nav=document.createElement('div');nav.className='nav';const prev=actionButton('← 上一条','',()=>move(-1));prev.disabled=state.offset<=0;const next=actionButton('下一条 →','',()=>move(1));nav.append(prev,next);card.append(nav)}
function referenceGroup(label,values,wikipedia){const group=document.createElement('div');const title=document.createElement('div');title.className='reference-label';title.textContent=label;group.append(title);const list=document.createElement('div');list.className='aliases';values.forEach(value=>{const wrapper=document.createElement('span');wrapper.className='reference-item';const item=document.createElement('button');item.type='button';item.className='reference-choice'+(wikipedia?' wikipedia':'');item.dataset.value=value;item.setAttribute('aria-pressed',String(state.selected===value));item.textContent=value;item.onclick=()=>select(value);wrapper.append(item);if(wikipedia){const link=document.createElement('a');link.className='reference-link';link.href='https://zh.wikipedia.org/wiki/'+encodeURIComponent(value.replaceAll(' ','_'));link.target='_blank';link.rel='noopener noreferrer';link.setAttribute('aria-label',`在 Wikipedia 打开 ${value}`);link.title='在 Wikipedia 打开';link.textContent='↗';wrapper.append(link)}list.append(wrapper)});group.append(list);return group}function actionButton(text,cls,fn){const b=document.createElement('button');b.type='button';b.className=cls;b.textContent=text;b.onclick=fn;return b}function select(value){state.selected=value;$('translation').value=value;updateSelection();updateLength()}function useOriginal(tag){select(tag);show('已填入原 tag，可调整大小写和空格后保存',false);$('translation').focus()}function updateSelection(){document.querySelectorAll('.candidate,.reference-choice').forEach(b=>{const on=b.dataset.value===state.selected;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on))})}function updateLength(){const el=$('length');if(!el)return;const n=[...state.selected].length;el.textContent=`${n}/80`;el.classList.toggle('warn',n>12)}function label(a){return({accept:'接受',skip:'跳过',no_suitable:'无合适译名'})[a]||a}
async function save(action){const payload={tag:state.item.tag,action};if(action==='accept'){if(!state.selected){show('请先选择或输入译名',true);return}payload.translation=state.selected}const res=await fetch('/api/decision',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok){show(data.error||'保存失败',true);return}if($('reviewStatus').value==='pending')state.offset=Math.max(0,state.offset);await load()}
async function undo(){const res=await fetch('/api/undo',{method:'POST'});const data=await res.json();if(!res.ok){show(data.error||'撤销失败',true);return}await load()}
function show(text,error){const el=$('message');if(el){el.textContent=text;el.classList.toggle('error',error)}}function move(delta){state.offset=Math.max(0,state.offset+delta);load().catch(e=>show(e.message,true))}function reset(){state.offset=0;load().catch(e=>$('summary').textContent=e.message)}
for(const id of ['category','candidateStatus','reviewStatus'])$(id).onchange=reset;$('query').oninput=()=>{clearTimeout(timer);timer=setTimeout(reset,250)};
document.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;if(e.key>='1'&&e.key<='9'){const value=state.item?.candidates[Number(e.key)-1];if(value){e.preventDefault();select(value)}}else if(e.key==='Enter'&&state.item){e.preventDefault();save('accept')}else if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}else if(e.key==='ArrowRight'){e.preventDefault();move(1)}});reset();
</script></body></html>"""
